/**
 * ***************************************************************************
 * Copyright (c) 2010 Qcadoo Limited
 * Project: Qcadoo Framework
 * Version: 1.2.0-SNAPSHOT
 *
 * This file is part of Qcadoo.
 *
 * Qcadoo is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation; either version 3 of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 * ***************************************************************************
 */
package com.qcadoo.report.api.pdf;

import static org.springframework.context.i18n.LocaleContextHolder.getLocale;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.lowagie.text.Document;
import com.lowagie.text.ExceptionConverter;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import com.qcadoo.localization.api.utils.DateUtils;
import com.qcadoo.model.api.Entity;
import com.qcadoo.report.api.ColorUtils;
import com.qcadoo.report.api.FontUtils;

/**
 * /** Helps the use of <CODE>PdfPageEvent</CODE> to provide page numbering, page footer and page header .
 * 
 * 
 */
public final class PdfPageNumbering extends PdfPageEventHelper {

    private static final String EMAIL = "email";

    /** The PdfTemplate that contains the total number of pages. */
    private PdfTemplate total;

    private final String page;

    private final String in;

    private final String companyName;

    private final String address;

    private final String phoneEmail;

    private final String generatedBy;

    private final String generationDate;

    /**
     * Constructor which prepare data for class events.
     * 
     * @param page
     *            page label
     * @param in
     *            in label
     * @param phone
     * @param company
     *            company entity
     * @param generatedBy
     *            generated by label
     * @param username
     */
    public PdfPageNumbering(final String page, final String in, final String phone, final Entity company,
            final String generatedBy, final String username) {
        super();
        this.page = page;
        this.in = in;

        StringBuilder footerData = new StringBuilder();
        footerData = footerData.append(generatedBy);
        footerData = footerData.append(" ");
        footerData = footerData.append(username);
        this.generatedBy = footerData.toString();

        this.generationDate = new SimpleDateFormat(DateUtils.L_DATE_TIME_FORMAT, getLocale()).format(new Date());

        if (company == null) {
            this.companyName = "";
            this.address = "";
            this.phoneEmail = "";
            return;
        }
        StringBuilder companyData = new StringBuilder();

        companyData = companyData.append(company.getStringField("name"));
        this.companyName = companyData.toString();

        if (company.getStringField("street") == null || company.getStringField("house") == null
                || company.getStringField("zipCode") == null || company.getStringField("city") == null) {
            this.address = "";
        } else {
            companyData.setLength(0);
            companyData = companyData.append(company.getStringField("street"));
            companyData = companyData.append(" ");
            companyData = companyData.append(company.getStringField("house"));
            if (company.getStringField("flat") != null) {
                companyData = companyData.append("/");
                companyData = companyData.append(company.getStringField("flat"));
            }
            companyData = companyData.append(", ");
            companyData = companyData.append(company.getStringField("zipCode"));
            companyData = companyData.append(" ");
            companyData = companyData.append(company.getStringField("city"));
            if (company.getStringField("country") != null) {
                companyData = companyData.append(", ");
                companyData = companyData.append(company.getStringField("country"));
            }
            this.address = companyData.toString();
        }

        if (company.getStringField("phone") == null) {
            if (company.getStringField(EMAIL) == null) {
                this.phoneEmail = "";
            } else {
                companyData.setLength(0);
                companyData = companyData.append("E-mail: ");
                companyData = companyData.append(company.getStringField(EMAIL));
                this.phoneEmail = companyData.toString();
            }
        } else {
            companyData.setLength(0);
            companyData = companyData.append(phone);
            companyData = companyData.append(": ");
            companyData = companyData.append(company.getStringField("phone"));
            if (company.getStringField(EMAIL) != null) {
                companyData = companyData.append(", ");
                companyData = companyData.append("E-mail: ");
                companyData = companyData.append(company.getStringField(EMAIL));
            }
            this.phoneEmail = companyData.toString();
        }
    }

    /**
     * @see com.lowagie.text.pdf.PdfPageEvent#onOpenDocument(com.lowagie.text.pdf.PdfWriter, com.lowagie.text.Document)
     */
    @Override
    public void onOpenDocument(final PdfWriter writer, final Document document) {
        total = writer.getDirectContent().createTemplate(100, 100);
        total.setBoundingBox(new Rectangle(-20, -20, 100, 100));
        try {
            ColorUtils.prepare();
            FontUtils.prepare();
        } catch (Exception e) {
            throw new ExceptionConverter(e);
        }
    }

    /**
     * @see com.lowagie.text.pdf.PdfPageEvent#onStartPage(com.lowagie.text.pdf.PdfWriter, com.lowagie.text.Document)
     */
    @Override
    public void onStartPage(final PdfWriter writer, final Document document) {
        PdfContentByte cb = writer.getDirectContent();
        cb.saveState();
        String text = page + " " + writer.getPageNumber() + " " + in + " ";
        float textBase = document.top() + 22;
        float textSize = FontUtils.getDejavu().getWidthPoint(text, 7);
        cb.setColorFill(ColorUtils.getLightColor());
        cb.setColorStroke(ColorUtils.getLightColor());
        cb.beginText();
        cb.setFontAndSize(FontUtils.getDejavu(), 7);
        float adjust = FontUtils.getDejavu().getWidthPoint("0", 7);
        cb.setTextMatrix(document.right() - textSize - adjust, textBase);
        cb.showText(text);
        cb.endText();
        cb.addTemplate(total, document.right() - adjust, textBase);
        cb.setLineWidth(1);
        cb.setLineDash(2, 2, 1);
        cb.moveTo(document.left(), document.top() + 12);
        cb.lineTo(document.right(), document.top() + 12);
        cb.stroke();
        cb.restoreState();
    }

    /**
     * @see com.lowagie.text.pdf.PdfPageEvent#onEndPage(com.lowagie.text.pdf.PdfWriter, com.lowagie.text.Document)
     */
    @Override
    public void onEndPage(final PdfWriter writer, final Document document) {
        PdfContentByte cb = writer.getDirectContent();
        cb.saveState();
        String text = page + " " + writer.getPageNumber() + " " + in + " ";
        float textBase = document.bottom() - 25;
        float textSize = FontUtils.getDejavu().getWidthPoint(text, 7);
        cb.setColorFill(ColorUtils.getLightColor());
        cb.setColorStroke(ColorUtils.getLightColor());
        cb.setLineWidth(1);
        cb.setLineDash(2, 2, 1);
        cb.moveTo(document.left(), document.bottom() - 10);
        cb.lineTo(document.right(), document.bottom() - 10);
        cb.stroke();
        cb.beginText();
        cb.setFontAndSize(FontUtils.getDejavu(), 7);
        float adjust = FontUtils.getDejavu().getWidthPoint("0", 7);
        cb.setTextMatrix(document.right() - textSize - adjust, textBase);
        cb.showText(text);

        textSize = FontUtils.getDejavu().getWidthPoint(generatedBy, 7);
        cb.setTextMatrix(document.right() - textSize, textBase - 10);
        cb.showText(generatedBy);

        textSize = FontUtils.getDejavu().getWidthPoint(generationDate, 7);
        cb.setTextMatrix(document.right() - textSize, textBase - 20);
        cb.showText(generationDate);

        cb.setTextMatrix(document.left(), textBase);
        cb.showText(companyName);
        float companyFooterLine = 10;
        if (!"".equals(address)) {
            cb.setTextMatrix(document.left(), textBase - companyFooterLine);
            cb.showText(address);
            companyFooterLine += 10;
        }
        if (!"".equals(phoneEmail)) {
            cb.setTextMatrix(document.left(), textBase - companyFooterLine);
            cb.showText(phoneEmail);
        }
        cb.endText();
        cb.addTemplate(total, document.right() - adjust, textBase);
        cb.restoreState();
    }

    /**
     * @see com.lowagie.text.pdf.PdfPageEvent#onCloseDocument(com.lowagie.text.pdf.PdfWriter, com.lowagie.text.Document)
     */
    @Override
    public void onCloseDocument(final PdfWriter writer, final Document document) {
        total.beginText();
        total.setFontAndSize(FontUtils.getDejavu(), 7);
        total.setTextMatrix(0, 0);
        total.showText(String.valueOf(writer.getPageNumber() - 1));
        total.endText();
    }

}
